import java.util.*;
import java.security.MessageDigest;
import java.math.BigInteger;
import java.security.NoSuchAlgorithmException;
class Main{
    public static String encryptMessage(String str)  throws NoSuchAlgorithmException {
        MessageDigest md = MessageDigest.getInstance("MD5");
        byte[] messageDigest = md.digest(str.getBytes());
        BigInteger no = new BigInteger(1, messageDigest);
        String hashtext = no.toString(16);
        while(hashtext.length() < 40){
            hashtext = "0"+hashtext;
        }
        return hashtext;
    }
    public static void main(String[] args) throws NoSuchAlgorithmException{
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter the message  : ");
        String str = sc.nextLine();
        System.out.println("Hashcode generated by MD5 for : "+str+ " is "+encryptMessage(str));
    }
}


/*
output

Enter the message  : 
message data
Hashcode generated by MD5 for : message data is 000000004605064d9e2ce534ff7259b3872ce05e
*/
