//change the file name to Main while running the program
import java.util.*;
import java.security.MessageDigest;
import java.math.BigInteger;
import java.security.NoSuchAlgorithmException;
class Main{
    public static String encryptMessage(String str)  throws NoSuchAlgorithmException {
        MessageDigest md = MessageDigest.getInstance("SHA-1");
        byte[] messageDigest = md.digest(str.getBytes());
        BigInteger no = new BigInteger(1, messageDigest);
        String hashtext = no.toString(16);
        while(hashtext.length() < 40){
            hashtext = "0"+hashtext;
        }
        return hashtext;
    }
    public static void main(String[] args) throws NoSuchAlgorithmException{
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter the message  : ");
        String str = sc.nextLine();
        System.out.println("Hashcode generated by SHA-1 for : "+str+ " is "+encryptMessage(str));
    }
}


/*
output

Enter the message  : 
datadata
Hashcode generated by SHA-1 for : datadata is b03881fcd505a6f2987289ae37488d514697466a
  */
